version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coworkingdb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coworkingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint: ["sh", "-c", "until nc -z db 3306; do sleep 2; done; java $JAVA_OPTS -jar app.jar --spring.profiles.active=$SPRING_PROFILES_ACTIVE"]
volumes:
  db_data:
